config/routes.rb
Gistflow::Application.routes.draw do
  match '/auth/github/callback'  => 'users#create'
  
  match '/logout' => 'sessions#destroy'
  
  match '/flow'      => 'posts#flow'
  match '/all'       => 'posts#index'
  match '/bookmarks' => 'posts#bookmarks'
  
  get :sitemap, to: 'sitemap#show', as: :xml
  
  namespace :account do
    post   '/followings/:user_id' => 'followings#create',  :as => :follow
    delete '/followings/:user_id' => 'followings#destroy'
                                  
    post   '/bookmarks/:post_id' => 'bookmarks#create', :as => :bookmark
    delete '/bookmarks/:post_id' => 'bookmarks#destroy'
                                  
    post   '/observings/:post_id' => 'observings#create', :as => :observe
    delete '/observings/:post_id' => 'observings#destroy'
    
    post   '/subscriptions/:tag_id' => 'subscriptions#create', :as => :subscribe
    delete '/subscriptions/:tag_id' => 'subscriptions#destroy'
    resources :subscriptions, only: :index

    resources :likes, only: [:create] do
      delete :destroy, on: :collection
    end
    resources :notifications, only: :index
    resource :settings, :only => [:show, :update]
    resource :profile, :only => [:show, :update]
  end
  
  resources :posts do
    collection do
      get :new_private
      get :leaderboard
    end

    resources :comments, only: [:create, :edit, :update, :destroy], module: :posts do
      collection do
        post :build
        post :preview
      end
    end
  end
  
  resource :search, only: :create
  
  get '/empty_search'  => 'searches#empty', as: 'nil_search'
  get '/search/:query' => 'searches#show',  as: 'show_search'
  
  resources :tags, only: :show do
    get :cloud, on: :collection
    resource :wiki, module: :tags, only: [:show, :edit, :update] do
      get 'history'
    end
  end
  
  resources :users, only: :show do
    scope module: :users do
      resources :followers, only: :index
      resources :followings, only: :index, path: '/following'
    end
  end
  
  namespace :admin do
    resources :users, only: :index
    resources :tags, only: [:index, :edit] do
      post :entity
    end
  end
  
  post '/api/markdown', to: 'markdown#create'
  
  resource :map
  
  root to: 'landings#show'
  match '*a', to: 'errors#not_found'
end

app/models/search.rb
class Search
  attr_reader :page_path
  
  delegate :url_helpers, :to => :'Rails.application.routes'
  
  def initialize(query)
    query.to_s.strip!
    @page_path = if query.present?
      case query[0]
      when '#' then
        url_helpers.tag_path(:id => query[1..-1])
      when '@' then
        url_helpers.user_path(query[1..-1])
      else
        url_helpers.show_search_path(:query => query)
      end
    else
      url_helpers.nil_search_path
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def create
    search = Search.new(params[:q])
    redirect_to search.page_path
  end
  
  def show
    @posts = Post.search(params[:query], page: params[:page])
    render :'search/show'
  end
  
  def empty
    render :'search/empty'
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def nothing_found(search)
    case search[0]
    when '#'
      "Tag \"#{search}\" is not found."
    when '@'
      "User with username \"#{search[1..-1]}\" is not found"
    else
      "Post contains \"#{search}\" is not found"
    end
  end
end

app/views/search/_form.html.slim
div class="search"
  = form_tag search_path do
    = search_field_tag :q, params[:q], :placeholder => "Search..", :id => nil
    = submit_tag '&#x21A9;'.html_safe

app/views/search/empty.html.slim
- window_title 'Empty search query'
section class="search"
  header class="primary"
    h1 Empty search query
  p We did not find anything because you did not enter the query.
  p Try again. You feeling lucky ;)

app/views/search/nothing.html.slim
- window_title 'Search results'
section class="search"
  header class="primary"
    h1 = "Search results for #{params[:q]}"
  p Sorry, but we didn't find anything.

app/views/search/show.html.slim
- window_title 'Search results'
section class="search"
  header class="primary"
    h1 = %{Search results for "#{params[:query]}"}
  = render :partial => 'posts/index', :locals => { :posts => @posts }
  - if @posts.empty?
    p Sorry, but we didn't find anything.