config/routes.rb
Gistflow::Application.routes.draw do
  match '/auth/github/callback'  => 'users#create'
  
  match '/logout' => 'sessions#destroy'
  
  match '/flow'      => 'posts#flow'
  match '/all'       => 'posts#index'
  match '/bookmarks' => 'posts#bookmarks'
  
  get :sitemap, to: 'sitemap#show', as: :xml
  
  namespace :account do
    post   '/followings/:user_id' => 'followings#create',  :as => :follow
    delete '/followings/:user_id' => 'followings#destroy'
                                  
    post   '/bookmarks/:post_id' => 'bookmarks#create', :as => :bookmark
    delete '/bookmarks/:post_id' => 'bookmarks#destroy'
                                  
    post   '/observings/:post_id' => 'observings#create', :as => :observe
    delete '/observings/:post_id' => 'observings#destroy'
    
    post   '/subscriptions/:tag_id' => 'subscriptions#create', :as => :subscribe
    delete '/subscriptions/:tag_id' => 'subscriptions#destroy'
    resources :subscriptions, only: :index

    resources :likes, only: [:create] do
      delete :destroy, on: :collection
    end
    resources :notifications, only: :index
    resource :settings, :only => [:show, :update]
    resource :profile, :only => [:show, :update]
  end
  
  resources :posts do
    collection do
      get :new_private
      get :leaderboard
    end

    resources :comments, only: [:create, :edit, :update, :destroy], module: :posts do
      collection do
        post :build
        post :preview
      end
    end
  end
  
  resource :search, only: :create
  
  get '/empty_search'  => 'searches#empty', as: 'nil_search'
  get '/search/:query' => 'searches#show',  as: 'show_search'
  
  resources :tags, only: :show do
    get :cloud, on: :collection
    resource :wiki, module: :tags, only: [:show, :edit, :update] do
      get 'history'
    end
  end
  
  resources :users, only: :show do
    scope module: :users do
      resources :followers, only: :index
      resources :followings, only: :index, path: '/following'
    end
  end
  
  namespace :admin do
    resources :users, only: :index
    resources :tags, only: [:index, :edit] do
      post :entity
    end
  end
  
  post '/api/markdown', to: 'markdown#create'
  
  resource :map
  
  root to: 'landings#show'
  match '*a', to: 'errors#not_found'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  DISPLAY_LIMIT = 15

  has_many :subscriptions
  has_many :taggings
  has_many :posts, {
    through: :taggings, source: :tag,
    conditions: { taggings: { taggable_type: 'Post' } }
  }
  has_many :comments, {
    through: :taggings, source: :tag,
    conditions: { taggings: { taggable_type: 'Comment' } }
  }
  has_many :aliases, class_name: :Tag, foreign_key: :entity_id
  belongs_to :entity, class_name: :Tag

  has_many :wikis

  before_create :build_default_wiki, unless: :wiki

  attr_accessible :name, as: :admin

  validates :name, presence: true, format: { with: /[a-z]+/ }

  scope :real, where(entity_id: nil)
  scope :for_cloud, select("name AS text, taggings_count AS weight, TEXTCAT('/tags/', tags.name) AS link").order('taggings_count DESC').limit(75)
  scope :popular, (lambda do |limit = 100|
    real.order('taggings_count desc').limit(limit)
  end)

  def alias?
    !!entity
  end

  def wiki
    @wiki ||= wikis(true).last
  end

  def to_s
    name
  end

  def name=(name)
    name.to_s.gsub!(/[\-_]/, '')
    name.downcase!
    write_attribute :name, name
  end

  def with_sign
    '#' << name.to_s
  end

  def to_param
    name
  end

  # Use this method for setup entity and update taggings and subscriptions
  def set_entity(tag)
    self.entity = tag
    Tag.transaction do
      save!
      relink_related_records_to_entity
      resubscribe_users_to_entity
    end
  end

protected

  def build_default_wiki
    wikis.build do |wiki|
      wiki.user    = User.gistflow
      wiki.content = 'Nothing to display yet.'
    end
  end

  def resubscribe_users_to_entity
    subscriptions.each do |subscription|
      conditions = { user_id: subscription.user_id, tag_id: entity_id }
      if Subscription.where(conditions).exists?
        subscription.destroy # don't dublicate subscriptions
      else
        subscription.update_attribute :tag_id, entity_id
      end
    end
    true
  end

  def relink_related_records_to_entity
    taggings.each do |tagging|
      conditions = {
        tag_id:        entity_id,
        taggable_type: tagging.taggable_type,
        taggable_id:   tagging.taggable_id
      }
      if Tagging.where(conditions).exists?
        tagging.destroy # don't dublicate taggings
      else
        tagging.update_attribute :tag_id, entity_id
      end
    end
    true
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  include Models::Cuttable
  include Models::Taggable
  
  belongs_to :user
  belongs_to :tag
  
  validates :user, :content, :tag, presence: true
  
  attr_accessible :content
  
  def title
    "#{tag.name}'s wiki".capitalize
  end
  
  # Creates a new version of wiki or return false
  def improve(attributes, user)
    new_wiki = tag.wikis.build(attributes) do |wiki|
      wiki.user = user
    end
    new_wiki.save ? new_wiki : false
  end
  
  def path
    "/tags/#{tag}/wiki"
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tags = Tag.includes(:entity).order(:name)
  end
  
  def edit
    @tag = find_tag(params[:id])
  end
  
  def entity
    @tag = find_tag(params[:tag_id])
    @entity = Tag.find(params[:tag][:entity_id])
    @tag.set_entity @entity
    redirect_to admin_tags_path
  end
  
protected
  
  def find_tag(id)
    Tag.find_by_name id
  end
end

app/controllers/tags/wikis_controller.rb
class Tags::WikisController < ApplicationController
  cache_sweeper :user_sweeper
  prepend_before_filter :authenticate!, only: [:edit, :update]
  
  def history
    @tag = find_tag(params[:tag_id])
    @wikis = @tag.wikis.includes(:user).order('id desc')
    @contributors = @wikis.map(&:user).uniq
  end
  
  def show
    @wiki = find_wiki(params[:tag_id])
  end
  
  def edit
    @wiki = find_wiki(params[:tag_id])
  end
  
  def update
    @wiki = find_wiki(params[:tag_id])
    if @wiki.improve(params[:wiki], current_user)
      redirect_to tag_wiki_path(@wiki.tag)
    else
      render :edit
    end
  end
  
protected
  
  def find_wiki(tag_name)
    find_tag(tag_name).wiki
  end
  
  def find_tag(tag_name)
    Tag.find_by_name(tag_name)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    if @tag = Tag.find_by_name(params[:id])
      redirect_to @tag.entity if @tag.alias?
      
      @posts = Post.not_private.tagged_with(@tag.name).page(params[:page])
      @subscription = current_user.subscriptions
        .find_or_initialize_by_tag_id(@tag.id) if user_signed_in?
    else
      render 'search/nothing'
    end
  end

  def cloud
    @tags = Tag.for_cloud
    render layout: 'sidebarless'
  end
end

app/helpers/wiki_helper.rb
module WikiHelper
  def wiki_preview(wiki)
    wiki_markup wiki.preview
  end
  
  def wiki_body(wiki)
    wiki_markup wiki.body
  end
  
protected
  
  def wiki_markup(text)
    html = Markdown.markdown(text)
    replaceable = Replaceable.new(html)
    replaceable.replace(:tags, :usernames)
    replaceable.to_s.html_safe
  end
end

app/views/tags/wikis/edit.html.slim
- window_title "Edit #{@wiki.tag.name}'s wiki"
section class="wiki"
  header class="primary"
    h1 = "Edit #{@wiki.tag.name}'s wiki"
  = form_for @wiki, :url => tag_wiki_path(@wiki.tag) do |f|
    - if @wiki.errors.any?
      ul class="errors"
        - @wiki.errors.full_messages.each do |message|
          li= message
    fieldset
      = f.text_area :content, :size => '40x12', :placeholder => "Preview<cut text=\"More under the cut\">Body", :class => 'hint'
    div class="actions group"
      div class="left"
        | This text will be parsed by 
        = link_to 'Markdown', 'http://daringfireball.net/projects/markdown/syntax', :class => 'highlight'
        | . See 
        = link_to 'hints', '#', :class => 'hints'
        |.
      div class="button-groups"
        div class="button-group"
          = f.submit commit_title, :class => 'button'
      = render :partial => 'shared/markdown_hints'

app/views/tags/wikis/history.html.slim
section class="contributors"
  header
    h1 Contributors
  - if @contributors.any?
    ul
      - @contributors.each do |user|
        li = link_to user, user
  - else
    p Nobody here yet.

section class="improvements"
  header
    h1 Improvements
  - if @wikis.size > 1
    p class="back" = link_to 'Back to wiki', tag_wiki_path(@tag)
    - @wikis.each_with_previous do |wiki, previous|
      - next unless previous
      div class="diff-container"
        div class="author"
          | Changes by
          = link_to wiki.user, wiki.user
          = " at #{wiki.created_at.to_formatted_s(:long)}"
        == Diffy::Diff.new(wiki.content, previous.content).to_s(:html)
  - else
    p No improvements yet.
  p class="back" = link_to 'Back to wiki', tag_wiki_path(@tag)

app/views/tags/wikis/show.html.slim
- window_title @wiki.title
article class="wiki"
  header.primary
    h1 = @wiki.title
  div class="markdown"
    = wiki_body(@wiki)
  footer class="group"
    div class="button-groups"
      div class="button-group"
        li = link_to "Return to tag", @wiki.tag, class: 'button'
      div class="button-group"
        - if user_signed_in?
          = link_to_subscribe @wiki.tag, onoff: true
        = link_to 'History', history_tag_wiki_path(@wiki.tag), class: 'button'
      - if user_signed_in?
        div class="button-group"
          = link_to 'Edit', edit_tag_wiki_path(@wiki.tag), class: 'button'