config/routes.rb
Gistflow::Application.routes.draw do
  match '/auth/github/callback'  => 'users#create'
  
  match '/logout' => 'sessions#destroy'
  
  match '/flow'      => 'posts#flow'
  match '/all'       => 'posts#index'
  match '/bookmarks' => 'posts#bookmarks'
  
  get :sitemap, to: 'sitemap#show', as: :xml
  
  namespace :account do
    post   '/followings/:user_id' => 'followings#create',  :as => :follow
    delete '/followings/:user_id' => 'followings#destroy'
                                  
    post   '/bookmarks/:post_id' => 'bookmarks#create', :as => :bookmark
    delete '/bookmarks/:post_id' => 'bookmarks#destroy'
                                  
    post   '/observings/:post_id' => 'observings#create', :as => :observe
    delete '/observings/:post_id' => 'observings#destroy'
    
    post   '/subscriptions/:tag_id' => 'subscriptions#create', :as => :subscribe
    delete '/subscriptions/:tag_id' => 'subscriptions#destroy'
    resources :subscriptions, only: :index

    resources :likes, only: [:create] do
      delete :destroy, on: :collection
    end
    resources :notifications, only: :index
    resource :settings, :only => [:show, :update]
    resource :profile, :only => [:show, :update]
  end
  
  resources :posts do
    collection do
      get :new_private
      get :leaderboard
    end

    resources :comments, only: [:create, :edit, :update, :destroy], module: :posts do
      collection do
        post :build
        post :preview
      end
    end
  end
  
  resource :search, only: :create
  
  get '/empty_search'  => 'searches#empty', as: 'nil_search'
  get '/search/:query' => 'searches#show',  as: 'show_search'
  
  resources :tags, only: :show do
    get :cloud, on: :collection
    resource :wiki, module: :tags, only: [:show, :edit, :update] do
      get 'history'
    end
  end
  
  resources :users, only: :show do
    scope module: :users do
      resources :followers, only: :index
      resources :followings, only: :index, path: '/following'
    end
  end
  
  namespace :admin do
    resources :users, only: :index
    resources :tags, only: [:index, :edit] do
      post :entity
    end
  end
  
  post '/api/markdown', to: 'markdown#create'
  
  resource :map
  
  root to: 'landings#show'
  match '*a', to: 'errors#not_found'
end

app/views/shared/_ads.html.slim
section class="ads"
  header class="primary"
    h1 Upcoming Conferences
  p
    = link_to image_tag('railsclub.png', alt: 'Railsclub'), 'http://railsclub.timepad.ru/event/29192'
  p
    = link_to 'Steve Klabnik', 'http://www.steveklabnik.com/'
    = ', '
    = link_to 'Xavier Noria', 'http://hashref.com/'
    = ', '
    = link_to 'Wynn Netherland', 'http://wynnnetherland.com/'
    = ', '
    = link_to 'Dirkjan Bussink', 'https://github.com/dbussink'
    = ', '
    = link_to 'Sau Sheong Chang', 'http://www.saush.com/'
    |  will speak at Railsclub
  p Moscow, September 15, 2012
  p
    strong = link_to 'Join event', 'http://railsclub.timepad.ru/event/29192'

app/views/shared/_creative_commons.html.erb
<p><a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/80x15.png" /></a></p>

app/views/shared/_facebook.html.slim
- return unless Rails.env.production?
section class="facebook"
  header class="primary"
    h1 Tell friends about us
  
  div class="fb-like" data-href="http://facebook.com/gistflow" data-send="false" data-width="340" data-show-faces="false"

app/views/shared/_gauges.html.erb
<script type="text/javascript">
  (function () {
    var yaz = document.createElement("script"); yaz.type = "text/javascript"; yaz.async = true;
    yaz.src = "http://50likes.com/tracker.js";
    document.getElementsByTagName("head")[0].appendChild(yaz);
  })();
</script>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30489562-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_markdown_hints.html.slim
div class="markdown_hints"
  ul
    li
      em = '*this is italic*'
    li
      strong = '**this is bold**'
    li [Google](http://google.com)
    li ![Image title](http://site.com/image.jpg)
    li * List item
    li > Blockquote
    li ~~~lang
    li code 
    li ~~~
    li `inline code`
    li @username to mention user
    li #tagname to tag post, comment or wiki

app/views/shared/_news.html.slim
section class="news"
  header class="primary"
    h1 Last updates
  p Check out #{link_to 'private posts', new_private_posts_path}. Use it for save your gists or share private code.

app/views/shared/_yandex_analytics.html.erb
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter14774479 = new Ya.Metrika({id:14774479,
                    clickmap:true,
                    accurateTrackBounce:true, webvisor:true});
        } catch(e) {}
    });
    
    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/14774479" style="position:absolute; left:-9999px;" alt="" /></div></noscript>